SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AdminDivision](
	[AdminDivisionID] [int] IDENTITY(1,1) NOT NULL,
	[Level] [int] NOT NULL,
	[Name] [nvarchar](30) NOT NULL,
	[SocrName] [nvarchar](10) NOT NULL,
	[CodeType] [int] NOT NULL,
 CONSTRAINT [PK_AdminDivisions_AdminDivisionsID] PRIMARY KEY CLUSTERED 
(
	[AdminDivisionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
