SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Land](
	[LandID] [int] IDENTITY(1,1) NOT NULL,
	[NumberLand] [nvarchar](50) NOT NULL,
	[NotaBene] [nvarchar](50) NULL,
 CONSTRAINT [PK_Land_LandID] PRIMARY KEY CLUSTERED 
(
	[LandID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
