SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/************************************************************
 * Generated by SoftTree SQL Assistant © 7.5.502
 * Time:   04.03.2018 21:11:29
 * Source: uspGetRoleForUser, uspLogError, uspPrintError
 ************************************************************/

/* [DispensaryMainTest].[dbo].[uspGetRoleForUser] */

/* DispensaryMain.[dbo].[uspGetRoleForUser] */

CREATE PROCEDURE [dbo].[uspGetRoleForUser]
(
	--@UserName NVARCHAR(50),
	@Role NVARCHAR(50) OUTPUT
)AS 
BEGIN 
	
SET @Role = ''
SELECT @Role = @Role + NAME +';' from sysmembers join sysusers on groupuid=uid where memberuid=user_id(USER_NAME())
SELECT SUBSTRING(@Role, 0, LEN(@Role)-1)
END

GO
