SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/************************************************************
 * Generated by SoftTree SQL Assistant © 7.5.502
 * Time:   04.03.2018 21:10:41
 * Source: uspGetRegisterByAddress, uspGetRegisterByApppTpr, uspGetRegisterByBenefitsCategory, 
 *         uspGetRegisterByBirthOfDay, uspGetRegisterByCustomerID, uspGetRegisterByGender, 
 *         uspGetRegisterByLand, uspGetRegisterByLastName
 ************************************************************/

/* [DispensaryMainTest].[dbo].[uspGetRegisterByAddress] */



/* [DispensaryMainTest].[dbo].[uspGetRegisterByApppTpr] */

/* [Dispensary].[dbo].[uspGetCustomerByApppTpr] */

/* Dispensary.[dbo].[vGetApppTpr] */

/****** Script for SelectTopNRows command from SSMS  ******/
CREATE PROCEDURE [dbo].[uspGetRegisterByApppTpr]
(@ID INT)
AS

BEGIN
	
	WITH CTE_ (CustomerID)
	AS(
		SELECT vgc.CustomerID FROM dbo.vGetCustomers AS vgc
		WHERE vgc.APPPTPRID =@ID
	)
	SELECT vgr.CustomerID,
           vgr.Diagnosis,
           vgr.FirstDeregister,
           vgr.FirstRegister,
           vgr.LandID,
           vgr.ModifiedDate,
           vgr.NotaBene,
           vgr.RegisterID,
           vgr.RegisterTypeID,
           vgr.SecondDeRegister,
           vgr.SecondRegister,
           vgr.SecondRegisterTypeID,
           vgr.WhyDeRegisterID,
           vgr.WhySecondDeRegisterID
	FROM dbo.vGetRegister AS vgr
	INNER JOIN CTE_ AS cte
	 ON cte.CustomerID = vgr.CustomerID  
END

GO

GRANT EXECUTE ON [dbo].[uspGetRegisterByApppTpr] TO [Sensitive_low] AS [dbo]
GO
