SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/************************************************************
 * Generated by SoftTree SQL Assistant © 7.5.502
 * Time:   04.03.2018 21:01:31
 * Source: uspGetAddressByBenefitsCategory, uspGetAddressByBirthOfDay, uspGetAddressByCustomerID, 
 *         uspGetAddressByGender, uspGetAddressByLand, uspGetAddressByLastName, uspSaveAddress
 ************************************************************/

/* [DispensaryMainTest].[dbo].[uspGetAddressByBenefitsCategory] */

/* [Dispensary].[dbo].[uspGetCustomerByBenefitsCategory] */

/****** Script for SelectTopNRows command from SSMS  
* 09.08.2016 Procedure for selecting Gender table
* ******/
CREATE PROCEDURE [dbo].[uspGetAddressByBenefitsCategory]
(@ID INT)
AS
 BEGIN
WITH CTE_InvalidBenefits(CustomerID)
AS(
	SELECT
		vgi.CustomerID
	FROM
		dbo.vGetInvalid AS vgi
		INNER JOIN dbo.vGetInvalid_BenefitsCategory AS vgibc
		ON vgi.InvalidID = vgibc.invID
		INNER JOIN dbo.vGetBenefitsCategory AS vgbc
		ON vgbc.BenefitsCategoryID = vgibc.BenefitsID
		INNER JOIN dbo.vGetCustomers AS vgc
		ON vgc.CustomerID = vgi.CustomerID
WHERE vgbc.BenefitsCategoryID = @ID AND vgc.Arch =0
		
		
)
SELECT  vga.AddressID,
        vga.AdminDivisionID,
        vga.City,
        vga.Country,
        vga.CustomerID,        
        vga.ModifiedDate,
        vga.NameStreet,
        vga.NumberApartment,
        vga.NumberHouse,
        vga.Region,
        vga.TypeStreetID FROM dbo.vGetAddress AS vga
  INNER JOIN CTE_InvalidBenefits AS cte
  ON cte.CustomerID = vga.CustomerID

      
  END

GO

GRANT EXECUTE ON [dbo].[uspGetAddressByBenefitsCategory] TO [Sensitive_low] AS [dbo]
GO
