SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/* [DispensaryMainTest].[dbo].[uspGetRegisterByCustomerID] */

/* [Dispensary].[dbo].[uspGetRegisterByCustomerID] */

/* Dispensary.[dbo].[uspGetRegister] */

CREATE PROCEDURE [dbo].[uspGetRegisterByCustomerID]
/***********************************************************
* Code generated by SoftTree SQL Assistant © v7.4.435
*
* Procedure description: This procedure is used for 
*                        retrieving records from table 
*                        Register
* Date:   14.04.2017 
* Author: DIMA KARPENKO
*
* Changes
* Date        Modified By            Comments
************************************************************
* 14.04.2017  DIMA KARPENKO     Initial version
************************************************************/
(
    @CustomerID int
)
AS
BEGIN
    SET NOCOUNT ON
    DECLARE @rowcount INT, @error INT

    -- search and return records
    SELECT RegisterID,
           FirstRegister,
           FirstDeregister,
           SecondRegister,
           Diagnosis,
           DataDiagnosis,
           RegisterTypeID,
           CustomerID,
           WhyDeRegisterID,
           LandID,
           Notabene,
           ModifiedDate 
    FROM [dbo].[Register]
    WHERE  CustomerID = @CustomerID

     -- capture operation completion code and number of records affected
	SELECT --@rowcount = @@ROWCOUNT, 
           @error = @@ERROR

	IF @error != 0
    BEGIN
    	-- cancel transaction, undo changes
        ROLLBACK TRANSACTION
		-- report error and exit with non-zero exit code
        RAISERROR('Unable to retrieve records. See previous message for details.', 16, 1) 
		RETURN @error
    END
  --  IF @rowcount = 0
  --  BEGIN
		---- report error and exit with non-zero exit code
  --      RAISERROR('Critical error. No records found for the specified criteria.', 16, 1) 
		--RETURN 1
  --  END 
  --  IF @rowcount > 1 
  --  BEGIN
		---- report error and exit with non-zero exit code
  --      RAISERROR('Warning. More than 1 record found for the specified criteria, while just 1 is expected.', 10, 1) 
		--RETURN 1
  --  END 

    -- commit changes and return 0 code indicating successful completion
	RETURN 0
END

GO

GRANT EXECUTE ON [dbo].[uspGetRegisterByCustomerID] TO [Sensitive_low] AS [dbo]
GO
