SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/************************************************************
 * Generated by SoftTree SQL Assistant © 7.5.502
 * Time:   04.03.2018 21:08:23
 * Source: uspFilterAddressByLand, uspFilterInvalidByLand, uspFilterRegisterByLands
 ************************************************************/

/* [DispensaryMainTest].[dbo].[uspFilterAddressByLand] */

/* [Dispensary].[dbo].[uspGetCustomerByLand] */

/****** Script for SelectTopNRows command from SSMS  
* 09.08.2016 Procedure for selecting Gender table
* ******/

/* [DispensaryMainTest].[dbo].[uspFilterInvalidByLand] */

/* [Dispensary].[dbo].[uspGetCustomerByLand] */

/****** Script for SelectTopNRows command from SSMS  
* 09.08.2016 Procedure for selecting Gender table
* ******/
CREATE PROCEDURE [dbo].[uspFilterInvalidByLand]
(@landid NVARCHAR(100))
AS
  BEGIN
DECLARE @sqlQuery NVARCHAR(200)
SET @sqlQuery =  N'SELECT
			vgr.CustomerID			
		FROM
			dbo.vGetRegister AS vgr	
			INNER JOIN dbo.vGetCustomers AS vgc
			ON vgc.CustomerID = vgr.CustomerID	
	WHERE vgr.LandID IN (' + @landid + N')AND vgc.Arch =0'	


CREATE TABLE #CustomerTempTotals
(
  CustomerID int
  
)
INSERT #CustomerTempTotals
(
    CustomerID
)
EXEC sp_executesql @sqlQuery

	SELECT  vgi.ChiperReceptID,
            vgi.CustomerID,          
            vgi.DataInvalidity,
            vgi.DateIncapable,
            vgi.DisabilityGroupID,
            vgi.Incapable,
            vgi.InvalidID,
            vgi.ModifiedDate,
            vgi.PeriodInvalidity FROM dbo.vGetInvalid AS vgi
	 INNER JOIN #CustomerTempTotals AS c 
	  ON c.CustomerID = vgi.CustomerID

DELETE #CustomerTempTotals      
  END

GO
