SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/************************************************************
 * Generated by SoftTree SQL Assistant © 7.5.502
 * Time:   04.03.2018 20:35:18
 * Source: vGetAddress, vGetAdminDivision, vGetApppTpr, vGetBenefitsCategory, vGetChiperRecept, 
 *         vGetDisabilityGroup, vGetGender, vGetInvalid, vGetInvalid_BenefitsCategory, 
 *         vGetLand, vGetRegister, vGetRegisterType, vGetTypeStreet, vGetWhyDeRegister
 ************************************************************/

/* [DispensaryMainTest].[dbo].[vGetAddress] */

/* DispensaryMain.[dbo].[vGetAddress] */

CREATE VIEW [dbo].[vGetAddress]
AS
SELECT [AddressID]
      ,[dbo].[Address].[CustomerID]
      ,[Region]
      ,[Country]
      ,[City]
      ,[AdminDivisionID]
      ,[TypeStreetID]
      ,[NameStreet]
      ,[NumberHouse]
      ,[NumberApartment]
      ,[ModifiedDate]
  FROM [dbo].[Address]

GO

GRANT SELECT ON [dbo].[vGetAddress] TO [Sensitive_low] AS [dbo]
GO
